"""add primary_contact_name to vendor

Revision ID: 010fdd75b802
Revises: 1dc3d0c3ada7
Create Date: 2026-03-06 21:05:47.845720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010fdd75b802'
down_revision = '1dc3d0c3ada7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_contact_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('shipping_address', sa.Text(), nullable=True))

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_contact_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('primary_contact_name')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('shipping_address')
        batch_op.drop_column('website')
        batch_op.drop_column('primary_contact_name')

    # ### end Alembic commands ###
