"""add_journal_metadata_columns

Revision ID: 1bd52969781a
Revises: f05a5e3f4c24
Create Date: 2026-03-05 20:52:50.592630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd52969781a'
down_revision = 'f05a5e3f4c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('source_module', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_journal_entries_vendor_id_vendors', 'vendors', ['vendor_id'], ['id'])
        batch_op.create_foreign_key('fk_journal_entries_customer_id_customers', 'customers', ['customer_id'], ['id'])

    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_journal_entries_customer_id_customers', type_='foreignkey')
        batch_op.drop_constraint('fk_journal_entries_vendor_id_vendors', type_='foreignkey')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('vendor_id')
        batch_op.drop_column('source_id')
        batch_op.drop_column('source_module')
        batch_op.drop_column('transaction_type')

    # ### end Alembic commands ###
