"""add_journal_metadata_columns

Revision ID: 1bd52969781a
Revises: f05a5e3f4c24
Create Date: 2026-03-05 20:52:50.592630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd52969781a'
down_revision = 'f05a5e3f4c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check journal_entries columns
    je_columns = [c['name'] for c in inspector.get_columns('journal_entries')]
    
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        if 'transaction_type' not in je_columns:
            batch_op.add_column(sa.Column('transaction_type', sa.String(length=50), nullable=True))
        if 'source_module' not in je_columns:
            batch_op.add_column(sa.Column('source_module', sa.String(length=20), nullable=True))
        if 'source_id' not in je_columns:
            batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        if 'vendor_id' not in je_columns:
            batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        if 'customer_id' not in je_columns:
            batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        
        # Check foreign keys
        existing_fks = [fk['name'] for fk in inspector.get_foreign_keys('journal_entries')]
        if 'fk_journal_entries_vendor_id_vendors' not in existing_fks:
            batch_op.create_foreign_key('fk_journal_entries_vendor_id_vendors', 'vendors', ['vendor_id'], ['id'])
        if 'fk_journal_entries_customer_id_customers' not in existing_fks:
            batch_op.create_foreign_key('fk_journal_entries_customer_id_customers', 'customers', ['customer_id'], ['id'])

    # Check journal_entry_lines columns
    jel_columns = [c['name'] for c in inspector.get_columns('journal_entry_lines')]
    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        if 'description' not in jel_columns:
            batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check journal_entry_lines columns
    jel_columns = [c['name'] for c in inspector.get_columns('journal_entry_lines')]
    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        if 'description' in jel_columns:
            batch_op.drop_column('description')

    # Check journal_entries columns and constraints
    je_columns = [c['name'] for c in inspector.get_columns('journal_entries')]
    je_fks = [fk['name'] for fk in inspector.get_foreign_keys('journal_entries')]
    
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        if 'fk_journal_entries_customer_id_customers' in je_fks:
            batch_op.drop_constraint('fk_journal_entries_customer_id_customers', type_='foreignkey')
        if 'fk_journal_entries_vendor_id_vendors' in je_fks:
            batch_op.drop_constraint('fk_journal_entries_vendor_id_vendors', type_='foreignkey')
        
        if 'customer_id' in je_columns:
            batch_op.drop_column('customer_id')
        if 'vendor_id' in je_columns:
            batch_op.drop_column('vendor_id')
        if 'source_id' in je_columns:
            batch_op.drop_column('source_id')
        if 'source_module' in je_columns:
            batch_op.drop_column('source_module')
        if 'transaction_type' in je_columns:
            batch_op.drop_column('transaction_type')

    # ### end Alembic commands ###
