"""add account_id to payments

Revision ID: 1dc3d0c3ada7
Revises: 498fbbc63dd1
Create Date: 2026-03-06 20:17:32.739998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc3d0c3ada7'
down_revision = '498fbbc63dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_account_id'), ['account_id'], unique=False)
        batch_op.create_foreign_key('fk_payments_account_id', 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payments_account_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_account_id'))
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
