"""Add asset and liability accounts to Tax

Revision ID: 498fbbc63dd1
Revises: 4d9edf0acd5d
Create Date: 2026-03-06 11:29:48.346579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498fbbc63dd1'
down_revision = '4d9edf0acd5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('liability_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_taxes_liability_account_id', 'accounts', ['liability_account_id'], ['id'])
        batch_op.create_foreign_key('fk_taxes_asset_account_id', 'accounts', ['asset_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_taxes_asset_account_id', type_='foreignkey')
        batch_op.drop_constraint('fk_taxes_liability_account_id', type_='foreignkey')
        batch_op.drop_column('liability_account_id')
        batch_op.drop_column('asset_account_id')

    # ### end Alembic commands ###
