"""Add account_id to vendor_payments

Revision ID: 4d9edf0acd5d
Revises: 1bd52969781a
Create Date: 2026-03-05 21:19:01.126248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9edf0acd5d'
down_revision = '1bd52969781a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_vendor_payments_account_id'), ['account_id'], unique=False)
        batch_op.create_foreign_key('fk_vendor_payments_account_id', 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vendor_payments_account_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_vendor_payments_account_id'))
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
