"""Add items table

Revision ID: 778c002440c9
Revises: 010fdd75b802
Create Date: 2026-03-20 15:15:10.445451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778c002440c9'
down_revision = 'e093d924d289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('sellable', sa.Boolean(), nullable=True),
    sa.Column('income_account_id', sa.Integer(), nullable=True),
    sa.Column('purchaseable', sa.Boolean(), nullable=True),
    sa.Column('expense_account_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['expense_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['income_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_taxes',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tax_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['tax_id'], ['taxes.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'tax_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_taxes')
    op.drop_table('items')
    # ### end Alembic commands ###
