"""Add database constraints and accounting periods

Revision ID: 85e8d1c1b583
Revises: a422cde8a53f
Create Date: 2026-02-28 14:29:47.002058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e8d1c1b583'
down_revision = 'a422cde8a53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_periods',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_bills_bill_number', ['bill_number'])
        batch_op.create_check_constraint('check_bill_total_positive', 'total >= 0')
        batch_op.create_check_constraint('check_bill_balance_positive', 'balance >= 0')
        batch_op.create_check_constraint('check_bill_due_date_after_issue', 'due_date >= issue_date')

    with op.batch_alter_table('bill_lines', schema=None) as batch_op:
        batch_op.create_check_constraint('check_bill_line_quantity_positive', 'quantity > 0')
        batch_op.create_check_constraint('check_bill_line_unit_cost_positive', 'unit_cost >= 0')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        # invoice_number is already unique in previous migrations probably, 
        # but let's ensure it if it's missing. Actually Sa already detected it as unique=True.
        batch_op.create_check_constraint('check_invoice_total_positive', 'total >= 0')
        batch_op.create_check_constraint('check_invoice_balance_positive', 'balance >= 0')
        batch_op.create_check_constraint('check_invoice_due_date_after_issue', 'due_date >= issue_date')

    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.create_check_constraint('check_invoice_line_quantity_positive', 'quantity > 0')
        batch_op.create_check_constraint('check_invoice_line_unit_price_positive', 'unit_price >= 0')

    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.create_check_constraint('check_journal_line_debit_positive', 'debit >= 0')
        batch_op.create_check_constraint('check_journal_line_credit_positive', 'credit >= 0')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_check_constraint('check_payment_amount_positive', 'amount > 0')

    with op.batch_alter_table('vendor_payments', schema=None) as batch_op:
        batch_op.create_check_constraint('check_vendor_payment_amount_positive', 'amount > 0')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_payments', schema=None) as batch_op:
        batch_op.drop_constraint('check_vendor_payment_amount_positive', type_='check')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('check_payment_amount_positive', type_='check')

    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.drop_constraint('check_journal_line_credit_positive', type_='check')
        batch_op.drop_constraint('check_journal_line_debit_positive', type_='check')

    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.drop_constraint('check_invoice_line_unit_price_positive', type_='check')
        batch_op.drop_constraint('check_invoice_line_quantity_positive', type_='check')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('check_invoice_due_date_after_issue', type_='check')
        batch_op.drop_constraint('check_invoice_balance_positive', type_='check')
        batch_op.drop_constraint('check_invoice_total_positive', type_='check')

    with op.batch_alter_table('bill_lines', schema=None) as batch_op:
        batch_op.drop_constraint('check_bill_line_unit_cost_positive', type_='check')
        batch_op.drop_constraint('check_bill_line_quantity_positive', type_='check')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_constraint('check_bill_due_date_after_issue', type_='check')
        batch_op.drop_constraint('check_bill_balance_positive', type_='check')
        batch_op.drop_constraint('check_bill_total_positive', type_='check')
        batch_op.drop_constraint('uq_bills_bill_number', type_='unique')

    op.drop_table('accounting_periods')
    # ### end Alembic commands ###
