"""add taxes table

Revision ID: e093d924d289
Revises: f9e52a4a09bc
Create Date: 2026-03-02 20:57:05.519671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e093d924d289'
down_revision = 'f9e52a4a09bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxes',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_line_taxes',
    sa.Column('bill_line_id', sa.Integer(), nullable=False),
    sa.Column('tax_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_line_id'], ['bill_lines.id'], ),
    sa.ForeignKeyConstraint(['tax_id'], ['taxes.id'], ),
    sa.PrimaryKeyConstraint('bill_line_id', 'tax_id')
    )
    op.create_table('invoice_line_taxes',
    sa.Column('invoice_line_id', sa.Integer(), nullable=False),
    sa.Column('tax_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['invoice_lines.id'], ),
    sa.ForeignKeyConstraint(['tax_id'], ['taxes.id'], ),
    sa.PrimaryKeyConstraint('invoice_line_id', 'tax_id')
    )
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal', sa.Numeric(precision=20, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax', sa.Numeric(precision=20, scale=2), nullable=True))

    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entry_lines_account'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_lines_entry'))
        batch_op.create_index(batch_op.f('ix_journal_entry_lines_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_lines_journal_entry_id'), ['journal_entry_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_customer'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice'))
        batch_op.create_index(batch_op.f('ix_payments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)

    with op.batch_alter_table('vendor_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_payments_bill'))
        batch_op.drop_index(batch_op.f('ix_vendor_payments_vendor'))
        batch_op.create_index(batch_op.f('ix_vendor_payments_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_payments_vendor_id'), ['vendor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_payments_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_payments_bill_id'))
        batch_op.create_index(batch_op.f('ix_vendor_payments_vendor'), ['vendor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_payments_bill'), ['bill_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payments_customer_id'))
        batch_op.create_index(batch_op.f('ix_payments_invoice'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_customer'), ['customer_id'], unique=False)

    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entry_lines_journal_entry_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_lines_account_id'))
        batch_op.create_index(batch_op.f('ix_journal_entry_lines_entry'), ['journal_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_lines_account'), ['account_id'], unique=False)

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_column('tax')
        batch_op.drop_column('subtotal')

    op.drop_table('invoice_line_taxes')
    op.drop_table('bill_line_taxes')
    op.drop_table('taxes')
    # ### end Alembic commands ###
