"""Remove tax_rate from settings

Revision ID: f05a5e3f4c24
Revises: e093d924d289
Create Date: 2026-03-03 19:42:17.666602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05a5e3f4c24'
down_revision = '778c002440c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_bill_lines_item_id_items', 'items', ['item_id'], ['id'])

    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_invoice_lines_item_id_items', 'items', ['item_id'], ['id'])

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('tax_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_rate', sa.NUMERIC(precision=5, scale=4), nullable=True))

    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('item_id')

    with op.batch_alter_table('bill_lines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
